### ISSUE TITLE
Tareas

### ISSUE THREAD

**Issue by jjhidalgar** [jaimehrubiks/SuperServerManagementGui#1]
- [x] Bug: El process List no wrapea el texto, es una linea horizontal infinita.
- [x] Bug: Pedir multiples processList a la vez, y evitar que se pida a los que no están online. Si se pide, pero el máster no devuelve nada porque el minion está offline, tampoco hay que crear la ventana.
- [x] Feature: El panel de Admin no hace nada. Hacer que esos botones hagan algo.
- [x] Feature: Añadir algo de CSS quizá.
- [x] Otros: El cambio a /mensajes/ hay que replicarlo en el otro proyecto. Y consecuentemente, debe ser el propio programa en swing el que cambie el \n por html, si así lo renderiza mejor, no la clase mensaje, que debe ser más genérica.
- [ ] Bug: Añadir el userId a cada petición del usuario. No hace falta mandar el nombre y pass, pero el userId estaría bien para que quede bien guardado en la base de datos de logs.
- [x] Replicar el minion log list para el user log list

Todo lo demás funciona.

**Comment by PJusue** [comment]
Falta añadir a la base de datos el resto de mensajes, solo se almacenan los de basicinfo y los de login
